---
title: "kremlin.ru_en"
description: "All items published on the English language version of the Kremlin's website"
author: Giorgio Comai
date: 2023-03-13
last-modified: 2023-03-13
categories: [dataset, Russian institutions, English language]
---

{{< include ./../_early_disclaimer.qmd >}}

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8,
                      fig.height = 4.5)

library("ggplot2")
library("dplyr", warn.conflicts = FALSE)

ggplot2::theme_set(new = theme_minimal(base_family = "Roboto Condensed"))

```

```{r}

library("castarter")

cas_set_options(
  base_folder = fs::path(fs::path_home_r(), 
                         "R",
                         "castarter_tadadit"),
  project = "Russian institutions",
  website = "kremlin.ru_en" 
)

corpus_df <- cas_read_db_contents_data() %>% 
  dplyr::collect()


max_date <- max(as.Date(corpus_df$date))

min_date <- min(as.Date(corpus_df$date))

total_items <- nrow(corpus_df)



```

```{r results='asis'}
body_text <- stringr::str_c(
  "**Dataset name**: kremlin.ru_en",
  "**Dataset description**: all items published on the English language version of the Kremlin's website",
  paste("**Start date**:", min_date),
  paste("**End date**:", max_date),
  paste("**Total items**:", scales::number(total_items)),
  paste("**Available columns**:", colnames(corpus_df) %>% 
          stringr::str_c(collapse = "; ")),
  paste("**License**:", "[Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/deed.ru)"),
  paste("**Link for download**: [kremlin.ru_en](https://github.com/giocomai/tadadit/releases/tag/kremlin.ru_en)"),
  sep = "\n\n")

cat(body_text)
```

::: callout-warning
## Warning: duplicate items

A significant number of items is effectively included twice in the current version of the dataset, as the same version of a speech is often posted both as "news" and as "transcript". Consider removing transcripts (all items with `transcripts` in the url), or items that have the same title and date. This issue will be addressed in a future release.
:::

```{r}
#| column: body
#| fig-width: 8
#| fig-height: 4.5
corpus_df |>
  mutate(year = lubridate::year(date)) |> 
  count(year) |> 
  ggplot(mapping = aes(x = year, y = n)) +
  geom_col() +
  scale_y_continuous(name = "", labels = scales::number) +
  scale_x_continuous(name = "", breaks = scales::pretty_breaks(n = 10)) +
  labs(
    title = "Number of items per year published on the English-language version of Kremlin.ru",
    subtitle = stringr::str_c(
      "Based on ",
      scales::number(nrow(corpus_df)),
      " items published between ",
      format.Date(x = min(corpus_df$date), "%d %B %Y"), 
      " and ",
      format.Date(x = max(corpus_df$date), "%d %B %Y")),
    caption = "Source: Giorgio Comai / tadadit.xyz"
  )
```

```{r}
words_per_day_df <- corpus_df |> 
  cas_count_total_words() |> 
  mutate(date = lubridate::as_date(date),
         string = "total words")

words_per_day_df |> 
  cas_summarise(period = "year", auto_convert = TRUE) |>
  rename(year = date) |> 
  ggplot(mapping = aes(x = year, y = n)) +
  geom_col() +
  scale_y_continuous(name = "", labels = scales::number) +
  scale_x_continuous(name = "", breaks = scales::pretty_breaks(n = 10)) +
  labs(title = "Number of words per year published on the the English-language version of Kremlin.ru",
       subtitle = stringr::str_c("Based on ",
                                 scales::number(nrow(corpus_df)),
                                 " items published between ",
                                 format.Date(x = min(corpus_df$date), "%d %B %Y"), 
                                 " and ",
                                 format.Date(x = max(corpus_df$date), "%d %B %Y")),
       caption = "Source: Giorgio Comai / tadadit.xyz")
```
