---
title: "Why Kyiv cannot possibly fix the 'root causes' of the conflict"
description: "No amount of unilateral Ukrainian concessions would address what Russia considers the 'root causes' of the conflict."
author: Giorgio Comai
date: 2025-05-05
last-modified: 2025-05-05
categories: [russia, ukraine, negotiations]
execute: 
  cache: false
editor: source
draft: false
---

## Context

When Vladimir Putin launched Russia's invasion of Ukraine in February 2022, [he claimed](http://en.kremlin.ru/events/president/news/67843) the purpose of the "special military operation" was to protect residents of Ukraine's Donbas region. "To this end" - he added - "[Russia] will seek to demilitarise and denazify Ukraine." On the same occasion, he made clear the conflict was not all about Ukraine, but really had its roots in "the fundamental threats which irresponsible Western politicians created for Russia" and a broad range of issues that all boil down to how "the United States does not believe it necessary to agree with Russia" on matters that are important to Moscow. When in 2025 Kremlin officials and Russian media refer to "the root causes of the conflict" that need to be resolved in order to establish long-term peace, they are really pointing to perceived lack of respect for Russia in a U.S.-led international order, not the rights and welfare of residents of the Donbas. 

The disconnect between these different layers of the conflict -- those closer to the reality on the ground in Ukraine, and those related to Russia's status in the international order -- complicate the establishment of a meaningful negotiating framework and hinder substantive public debate around these matters. If the "root causes" of the conflict lie in Russia's relations with the West, no amount of unilateral Ukrainian concessions -- least of all territorial concessions -- would lead to a satisfactory outcome for Russia. Putin's desired outcome cannot possibly stem from a decision taken in Kyiv.

Ukraine, of course, remains central to Russia's interests. But once the West finally accepts Moscow's vision for a security framework that fully acknowledges that it is "necessary to agree with Russia" on all important issues and recognise Russia's pre-eminent interest in its neighbourhood and beyond, then all the rest logically follows, including on matters related to Ukraine. In this vision, once Western geopolitical ambitions and weapons are removed from Ukraine, Ukraine would inevitably fall back within the Russian political and cultural space where it naturally belongs.

Western quiescence to Russia's demands and Moscow's neo-imperial design to control Ukraine, and indeed subsume it in the Russian cultural and political space along with Belarus, are inextricably intertwined, as one set of objectives cannot be achieved without the other. 

## What the Kremlin wants

For a long time, the Kremlin has been insisting that Russia must be "respected" by the West. Observing that the desired level of deference would not be forthcoming, on multiple occasions Moscow decided to use force to demonstrate that it cannot be ignored, as well as the West's impotence: Russia's annexation of Crimea and its later military intervention in Syria both served to advance this argument. The "special military operation" launched in February 2022 was (and still is) supposed to make this point more decisively.

The ongoing contacts initiated after Donald Trump's return to the White House between Russia and the United States are a considerable success for the Kremlin, as Washington and Moscow negotiating over Ukraine and long-term security arrangements in Europe on Moscow's terms is after all what Putin had been demanding from the outset. It soon became clear, however, that the sides cannot hold substantive debates on security matters due to a mismatch of expectations about what the negotiations would really be about and who should be making concessions. 

The U.S. leadership seemed to expect that forcing Ukraine to accept territorial losses while achieving some material gains in the process was a sure recipe to end the war and move on to other business. Having observed the intractability of security issues based on these premises, the U.S. leadership has been trying to move on to other business -- including with Moscow -- regardless, without having achieved much besides having disparaged all of its most established allies in the process. Indeed, reflecting the renewed focus of the negotiations, both [the United States](https://www.bbc.co.uk/sounds/play/m0029q9g) and [Russia](https://www.bbc.com/russian/podcasts/p076qqzl/p0l2xhrx) have chosen business developers to lead contacts across sides.


The Kremlin is still pursuing the very same objectives it set at the beginning of the full scale invasion in 2022: on the one hand, forcibly reshape the security architecture in Europe and force the West to "respect" Russia's leading role on the global stage; on the other, reduce Ukraine to a pliant and inoffensive client, to be integrated in the "Russian world" along with Belarus. At the same time, Moscow is still actively pursuing its immediate goals: a change of leadership in Kyiv -- a first step towards the more radical purge of the Ukrainian national political and cultural elite it understood as "denazification" -- and considerable limitations to Ukraine's army -- its "demilitarization" objective. 

## What about "residents of the Donbas"?

There is, however, one exception to this apparent consistency: the humanitarian component, much touted in the early phases of the war along with the need to save and liberate residents of the Donbas has [all but disappeared from Russia's official rhetoric](../2025-05-donbas-residents-root-causes/). Images from a few cities such as Mariupol chosen to showcase reconstruction efforts are presented in the media as useful background to visits by federal officials, but they are hardly central to war-legitimising narratives. Russia's invasion has wrecked the life and livelihood of millions of people living in these areas to the extent that even Russian authorities and news media have mostly stopped insisting this was all done primarily for the welfare of the people that used to live in towns that are now in ruins.

Indeed, [the topic of "residents of the Donbas"](../2025-05-donbas-residents-root-causes/) has slowly faded away from public attention in Russia after the first months of the war. There is even less talk about residents of Kherson and Zaporizhzhia regions, who, in line with the Kremlin's original rhetoric, should either be liberated or eagerly expecting to be freed from under Kyiv's yoke. Even the territories themselves may feature in reporting in ongoing fighting, but not really as a much coveted land that needs to be liberated and returned to the motherland. There is no hint that the final war objective is to establish full control of those regions, and that reaching those administrative boundaries would determine a victorious end to the war for Russia. 

This is part of the reason why, as the U.S. leadership started its push for settling a deal based on territorial concessions, the Russian side talked ever more insistently about the need to deal with the "root causes" of the conflict, while smoothly shifting the focus of negotiations away from the war and on to business matters, in a manoeuvre that indirectly gets the Kremlin closer to all of its goals much more than territorial or even political concessions from Kyiv ever could. 


## Conclusions

Russia's invasion of Ukraine is a neo-imperial [performative war](https://doi.org/10.1080/09636412.2019.1551567) waged for asserting Russia's status both at the regional and global level. In the current international environment heavily influenced by an erratic U.S. leadership, there are major debates in Europe on the best way forward for establishing long-lasting peace on the continent, with no easy solutions in sight. Accepting that no amount of plausible concessions from Kyiv would put an end to the conflict is a necessary premise for more substantive policy debates in Europe and elsewhere. 





::: {.callout-note}
## Credits and disclaimers

This project is realized with the support of the Unit for Analysis, Policy Planning, Statistics and Historical Documentation -  Directorate General for Public and Cultural Diplomacy of the Italian Ministry of Foreign Affairs and International Cooperation, in accordance with Article 23 ‒ bis of the Decree of the President of the Italian Republic 18/1967.

The views expressed are solely those of the authors and do not necessarily reflect the views of the Ministry of Foreign Affairs and International Cooperation.

See [project page](https://www.balcanicaucaso.org/eng/Projects2/Framings-of-Russia-s-invasion-of-Ukraine-in-Russia-s-pro-Kremlin-public-discourse).

:::

